validation:
   name         : Dummy validation
   description  : This is just a dummy validation for demo proposes.
   timeInterval : 5000
   waitForFinish: true
   onlyOnEvent  : true
   exec         : >
      var ret = [];

      var vals = scope.getCurrentValues();
       
      if (ow.format.dateDiff.inSeconds(new Date(vals["Dir Name"].date)) > 30) {
         //ret.push(new nWarning(nWarning.LEVEL_HIGH, "Dummy low warning", "This is just a dummy low warning"));
      } else {
         this.closeWarning("Dummy low warning");
      }
 
      ret.push(new nWarning(nWarning.LEVEL_LOW, "Dummy warning", "Teh difference is now " + ow.format.dateDiff.inSeconds(new Date(vals["Dir Name"].date)))); 
    
      return ret;
