validation:
   name         : Error flows validation
   description  : Simple validation to generate a warning if an error is found on a flow not older than a day.
   chSubscribe  : nattrmon::cvals
   waitForFinish: false
   execFrom     : nValidation_Generic
   execArgs     :
      checks:
         - attrPattern      : "Server status/.+in error flows"
           expr             : >
              {{owFormat_dateDiff_inSeconds value.Date void void}} <= (24*60*60) &&
              (! ('{{{escape value.Exception}}}'.match(/server shutdown/)) )
           warnLevel        : HIGH
           warnTitleTemplate: "Flow {{value.Category}} - {{value.Flow}} ({{value.Version}})"
           warnDescTemplate : "The flow {{value.Category}} - {{value.Flow}} ({{value.Version}}) ended in error at {{value.Date}} with run id {{value.[Run ID]}}, started by the user '{{value.User}}'. The exception was: '{{value.Exception}}'"