output:
   name         : Output EMail warning
   chSubscribe  : nattrmon::warnings
   wairForFinish: true
   onlyForEvent : true
   execFrom     : nOutput_EmailWarnings
   execArgs     : 
      to                    : 
        - myemail@email.com
        - mycolleague@email.com
      subject               : "[nattrmon] Sample"
      from                  : nattrmon@email.com
      server                : smtp.email.com
      port                  : 465
      credentials           :
        user    : mylogin
        password: mypassword
      debug                 : false
      #warnTypes             :
      #  - High
      #  - Medium
      #include               :
      #  - Warning to include
      #exclude               :
      #  - Warning to exclude
      #groupBySimilarity     : 10
      #descriptionLimit      : 20