input: 	
   name         : Directory Name
   cron         : "*/1 * * * *"
   waitForFinish: true
   onlyOnEvent  : true
   exec         : >
      var ret = {};
      ret["Dir Name"] = $from(io.listFiles("/root/test").files).equals("isFile", true).select(function(r) {
         return { 
            "filename"    : r.filename,
            "size"        : ow.format.toBytesAbbreviation(r.size),
            "lastModified": ow.format.timeago(new Date(r.lastModified))
         }
      });

      return ret;