input: 	
   name         : Semaphores 
   cron         : "*/5 * * * * *"
   waitForFinish: true
   onlyOnEvent  : true
   execFrom     : nInput_CBPMSemaphores
   execArgs     : 
      chKeys      : raidServers