input: 	
   name         : Sessions
   cron         : "*/5 * * * * *"
   waitForFinish: true
   onlyOnEvent  : true
   execFrom     : nInput_Sessions
   execArgs     : 
      chKeys      : raidServers