input: 	
   name         : Shell Command
   cron         : "*/1 * * * *"
   waitForFinish: true
   onlyOnEvent  : true
   execFrom     : nInput_Shell
   execArgs     : 
     attrTemplate: Commands/Script
     cmd         : /some/shell/command
     jsonParse   : true