input:
   name    : Remote nAttrMon
   cron    : "*/1 * * * *"
   execFrom: nInput_RemoteChannel
   execArgs:
      url         : http://nattrmon:nattrmon@some.remote.server:8090/chs/cvals
      include     :
        - Attr1
        - My attribute 2
        - Attr3
      exclude     :
        - Attr4
      attrTemplate: Remote/{{id}}